* Overview
The colossal camera is built using two Raspberry Pi's: one to serve as the camera (camerapi) and one to interface with a display screen (displaypi).
* Installation
Copy .service files to /etc/systemd/system/
On the camerapi, enable using,
systemctl enable camera.service 

On the displaypi, enable using
systemctl enable reverse_mosaic.service show_image.service

Enable SSH on camerapi and displaypi
$ raspi-config

Generate ssh key on the camerapi, copy to the displaypi
$ ssh-keygen
$ ssh-copy-id pi@display

Install python requirements on camerapi
$ pip3 install -r requirements.txt

Enable camera on camerapi
$ raspi-config

** Setup displaypi as AP
Setup the display pi as an access point that the camerapi connects to.
Most tutorials ultimately forward traffic to the internet through the host ethernet. This adds complexity and isn't desired in this project.
https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md

$ apt install hostapd dnsmasq

$ sudo systemctl unmask hostapd
$ sudo systemctl enable hostapd

sudo DEBIAN_FRONTEND=noninteractive apt install -y netfilter-persistent iptables-persistent

* Reverse Mosaic
** logfile
information is stored in the following format
tilepath, [row,col,h,s,v], [row,col,h,s,v]

where h is hue, s saturation and v value. Each set of values corresponds to a position and color that has been chosen for that tile.

